// lib/document-config.ts
// Annex and Document type registry — single source of truth for the modular document builder.
// Annex config toggles (per document) are stored in SystemConfig under "document_annex_config".

export type AnnexSlug =
  | 'hea-sa'
  | 'open-solar'
  | 'client-photos-intake'
  | 'client-photos-followup'
  | 'installer-photos'
  | 'financial-outcomes'
  | 'system-spec'
  | 'site-assessment'
  | 'nmi-data'

export type DocSlug =
  | 'job-card'
  | 'electrical-works-proposal'
  | 'wholesale-order'
  | 'work-order'
  | 'completion-report'
  | 'finance-pack'
  | 'grid-connection'

export type AnnexStatus = 'available' | 'planned'

export type AnnexDef = {
  slug: AnnexSlug
  name: string
  description: string
  source: string
  driveSubfolder: string
  filePattern: string
  status: AnnexStatus
}

export type AnnexAssignment = {
  slug: AnnexSlug
  defaultEnabled: boolean
}

export type DocumentDef = {
  slug: DocSlug
  name: string
  description: string
  audience: string
  filePattern: string
  driveSubfolder: string
  annexes: AnnexAssignment[]
}

// Stored per-document config (overrides defaults). Persisted in SystemConfig.
export type DocumentAnnexOverrides = Partial<Record<AnnexSlug, boolean>>
export type DocumentConfig = Partial<Record<DocSlug, DocumentAnnexOverrides>>

// ── Annex registry ─────────────────────────────────────────────────────────────
// Naming convention: {JOB-ID}-annex-{slug}-{Client-Name}-{YYYY-MM-DD}.pdf

export const ANNEX_REGISTRY: AnnexDef[] = [
  {
    slug: 'hea-sa',
    name: 'HEA Solar Analysis',
    description:
      'System sizing, annual savings, payback period, and bill reduction modelling generated by the HEA Solar Analyser tool.',
    source: 'HEA Solar Analyser (GAS)',
    driveSubfolder: '01-quotes/',
    filePattern: '{JOB-ID}-annex-hea-sa-{Client-Name}-{YYYY-MM-DD}.pdf',
    status: 'planned',
  },
  {
    slug: 'open-solar',
    name: 'Open Solar Report',
    description:
      'Technical system design, shading analysis, irradiance map, and annual production estimates from OpenSolar.',
    source: 'Manual upload → GAS Drive (02-proposals/)',
    driveSubfolder: '02-proposals/',
    filePattern: '{JOB-ID}-annex-open-solar-{Client-Name}-{YYYY-MM-DD}.pdf',
    status: 'available',
  },
  {
    slug: 'client-photos-intake',
    name: 'Client Intake Photos',
    description:
      'Roof, switchboard, and battery location photos submitted by the client during the intake form.',
    source: 'Intake form → GAS Drive (05-photos/)',
    driveSubfolder: '05-photos/',
    filePattern: '{JOB-ID}-annex-client-photos-{Client-Name}-{YYYY-MM-DD}.pdf',
    status: 'available',
  },
  {
    slug: 'client-photos-followup',
    name: 'Client Follow-up Photos',
    description:
      'Additional site photos sent by the client after intake, typically captured during the estimation site visit.',
    source: 'Manual upload → GAS Drive (05-photos/)',
    driveSubfolder: '05-photos/',
    filePattern: '{JOB-ID}-annex-client-photos-followup-{Client-Name}-{YYYY-MM-DD}.pdf',
    status: 'available',
  },
  {
    slug: 'installer-photos',
    name: 'Post-Install Installer Photos',
    description:
      'Panel array, inverter, meter box, and switchboard photos uploaded by the installer via the HEA Installer App after commissioning.',
    source: 'HEA Installer App → GAS Drive (05-photos/)',
    driveSubfolder: '05-photos/',
    filePattern: '{JOB-ID}-annex-installer-photos-{Client-Name}-{YYYY-MM-DD}.pdf',
    status: 'available',
  },
  {
    slug: 'financial-outcomes',
    name: 'Financial Outcomes',
    description:
      'Detailed ROI analysis, year-by-year bill savings, feed-in tariff income, system payback period, and carbon offset figures.',
    source: 'Calculated from HEA SA data',
    driveSubfolder: '02-proposals/',
    filePattern: '{JOB-ID}-annex-financial-outcomes-{Client-Name}-{YYYY-MM-DD}.pdf',
    status: 'available',
  },
  {
    slug: 'system-spec',
    name: 'System Specification',
    description:
      'Panel make/model/count, inverter specifications, battery model and capacity, EV charger, and DC/AC wiring summary.',
    source: 'OpenSolar / job data',
    driveSubfolder: '01-quotes/',
    filePattern: '{JOB-ID}-annex-system-spec-{Client-Name}-{YYYY-MM-DD}.pdf',
    status: 'available',
  },
  {
    slug: 'site-assessment',
    name: 'Site Assessment',
    description:
      'Roof orientation, pitch, shading conditions, switchboard capacity, phase supply, and grid connection constraints from intake data.',
    source: 'Intake form data',
    driveSubfolder: '06-jobfiles/',
    filePattern: '{JOB-ID}-annex-site-assessment-{Client-Name}-{YYYY-MM-DD}.pdf',
    status: 'available',
  },
  {
    slug: 'nmi-data',
    name: 'NMI & Grid Data',
    description:
      'National Metering Identifier, DNSP details, current tariff, and historical consumption data retrieved via Powercor.',
    source: 'Powercor NMI platform → GAS Drive (00-nmi-data/)',
    driveSubfolder: '00-nmi-data/',
    filePattern: '{JOB-ID}-annex-nmi-data-{Client-Name}-{YYYY-MM-DD}.pdf',
    status: 'available',
  },
]

// ── Document registry ──────────────────────────────────────────────────────────
// Base naming: {JOB-ID}-{descriptor}-{Client-Name}-{YYYY-MM-DD}.pdf

export const DOCUMENT_REGISTRY: DocumentDef[] = [
  {
    slug: 'job-card',
    name: 'Job Card',
    description:
      'Internal operations document carried by installers on-site. Contains client contact, roof data, system spec, and all technical details needed to complete the installation.',
    audience: 'Installers',
    filePattern: '{JOB-ID}-job-card-{Client-Name}-{YYYY-MM-DD}.pdf',
    driveSubfolder: '06-jobfiles/',
    annexes: [
      { slug: 'hea-sa',                defaultEnabled: true },
      { slug: 'system-spec',           defaultEnabled: true },
      { slug: 'site-assessment',       defaultEnabled: true },
      { slug: 'nmi-data',              defaultEnabled: true },
      { slug: 'client-photos-intake',  defaultEnabled: true },
      { slug: 'client-photos-followup',defaultEnabled: false },
      { slug: 'open-solar',            defaultEnabled: false },
      { slug: 'financial-outcomes',    defaultEnabled: false },
      { slug: 'installer-photos',      defaultEnabled: false },
    ],
  },
  {
    slug: 'electrical-works-proposal',
    name: 'Electrical Works Proposal',
    description:
      'Client-facing pre-sale proposal. Outlines the proposed system, what is included, T&Cs, and sells the value of the installation back to the client to reduce drop-off.',
    audience: 'Client',
    filePattern: '{JOB-ID}-electrical-works-proposal-{Client-Name}-{YYYY-MM-DD}.pdf',
    driveSubfolder: '02-proposals/',
    annexes: [
      { slug: 'hea-sa',                defaultEnabled: true },
      { slug: 'open-solar',            defaultEnabled: true },
      { slug: 'financial-outcomes',    defaultEnabled: true },
      { slug: 'system-spec',           defaultEnabled: true },
      { slug: 'client-photos-intake',  defaultEnabled: false },
      { slug: 'client-photos-followup',defaultEnabled: false },
      { slug: 'nmi-data',              defaultEnabled: false },
      { slug: 'site-assessment',       defaultEnabled: false },
      { slug: 'installer-photos',      defaultEnabled: false },
    ],
  },
  {
    slug: 'wholesale-order',
    name: 'Wholesale / Parts Order',
    description:
      'Sent to the wholesaler to order stock for a job. Contains system specifications and quantities. No financial or client-sensitive information included.',
    audience: 'Wholesaler / Supplier',
    filePattern: '{JOB-ID}-wholesale-order-{Client-Name}-{YYYY-MM-DD}.pdf',
    driveSubfolder: '06-jobfiles/',
    annexes: [
      { slug: 'system-spec',           defaultEnabled: true },
      { slug: 'hea-sa',                defaultEnabled: false },
      { slug: 'site-assessment',       defaultEnabled: false },
      { slug: 'open-solar',            defaultEnabled: false },
      { slug: 'financial-outcomes',    defaultEnabled: false },
      { slug: 'client-photos-intake',  defaultEnabled: false },
      { slug: 'nmi-data',              defaultEnabled: false },
    ],
  },
  {
    slug: 'work-order',
    name: 'Subcontractor Work Order',
    description:
      'Issued to subcontractors or licensed electricians hired to assist on a job. Defines scope of works, site address, system spec, and any site access conditions.',
    audience: 'Subcontractors / Workers',
    filePattern: '{JOB-ID}-work-order-{Client-Name}-{YYYY-MM-DD}.pdf',
    driveSubfolder: '06-jobfiles/',
    annexes: [
      { slug: 'system-spec',           defaultEnabled: true },
      { slug: 'site-assessment',       defaultEnabled: true },
      { slug: 'client-photos-intake',  defaultEnabled: true },
      { slug: 'client-photos-followup',defaultEnabled: false },
      { slug: 'hea-sa',                defaultEnabled: false },
      { slug: 'open-solar',            defaultEnabled: false },
      { slug: 'financial-outcomes',    defaultEnabled: false },
      { slug: 'nmi-data',              defaultEnabled: false },
    ],
  },
  {
    slug: 'completion-report',
    name: 'Post-Install Completion Report',
    description:
      'Sent to the client after a successful installation. Confirms the system is commissioned, includes warranty information, and provides a photo record of the completed work.',
    audience: 'Client',
    filePattern: '{JOB-ID}-completion-report-{Client-Name}-{YYYY-MM-DD}.pdf',
    driveSubfolder: '04-installed/',
    annexes: [
      { slug: 'installer-photos',      defaultEnabled: true },
      { slug: 'system-spec',           defaultEnabled: true },
      { slug: 'financial-outcomes',    defaultEnabled: true },
      { slug: 'hea-sa',                defaultEnabled: false },
      { slug: 'open-solar',            defaultEnabled: false },
      { slug: 'client-photos-intake',  defaultEnabled: false },
      { slug: 'nmi-data',              defaultEnabled: false },
      { slug: 'site-assessment',       defaultEnabled: false },
    ],
  },
  {
    slug: 'finance-pack',
    name: 'Finance Support Pack',
    description:
      "Assembled for the client's finance broker or lender. Provides system value justification, financial outcome projections, and HEA's credentials as a licensed installer.",
    audience: 'Finance Broker / Lender',
    filePattern: '{JOB-ID}-finance-pack-{Client-Name}-{YYYY-MM-DD}.pdf',
    driveSubfolder: '03-signed/',
    annexes: [
      { slug: 'hea-sa',                defaultEnabled: true },
      { slug: 'financial-outcomes',    defaultEnabled: true },
      { slug: 'system-spec',           defaultEnabled: true },
      { slug: 'open-solar',            defaultEnabled: false },
      { slug: 'nmi-data',              defaultEnabled: false },
      { slug: 'client-photos-intake',  defaultEnabled: false },
      { slug: 'site-assessment',       defaultEnabled: false },
      { slug: 'installer-photos',      defaultEnabled: false },
    ],
  },
  {
    slug: 'grid-connection',
    name: 'Grid Connection Application',
    description:
      'Submitted to the DNSP (Powercor / CitiPower) to apply for network connection approval prior to installation. Contains NMI data, system spec, and site details.',
    audience: 'DNSP / Network Operator',
    filePattern: '{JOB-ID}-grid-connection-{Client-Name}-{YYYY-MM-DD}.pdf',
    driveSubfolder: '06-jobfiles/',
    annexes: [
      { slug: 'nmi-data',              defaultEnabled: true },
      { slug: 'system-spec',           defaultEnabled: true },
      { slug: 'site-assessment',       defaultEnabled: true },
      { slug: 'open-solar',            defaultEnabled: false },
      { slug: 'hea-sa',                defaultEnabled: false },
      { slug: 'financial-outcomes',    defaultEnabled: false },
    ],
  },
]

// ── Helpers ────────────────────────────────────────────────────────────────────

export function getAnnexBySlug(slug: AnnexSlug): AnnexDef | undefined {
  return ANNEX_REGISTRY.find((a) => a.slug === slug)
}

// Returns the resolved enabled/disabled state for each annex on a document,
// merging saved DB overrides over the registry defaults.
export function resolveDocumentConfig(
  docSlug: DocSlug,
  savedConfig: DocumentConfig
): Record<AnnexSlug, boolean> {
  const docDef = DOCUMENT_REGISTRY.find((d) => d.slug === docSlug)
  if (!docDef) return {} as Record<AnnexSlug, boolean>
  const overrides = savedConfig[docSlug] ?? {}
  const result = {} as Record<AnnexSlug, boolean>
  for (const assignment of docDef.annexes) {
    result[assignment.slug] = overrides[assignment.slug] ?? assignment.defaultEnabled
  }
  return result
}
